const nav=document.querySelector('.nav'),glow=document.querySelector('.cursor-glow');
addEventListener('scroll',()=>nav.classList.toggle('compact',scrollY>45),{passive:true});
addEventListener('pointermove',e=>{if(glow){glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'}});
const themeButton=document.querySelector('.theme');
const applyTheme=dark=>{document.body.classList.toggle('night-mode',dark);document.documentElement.style.colorScheme=dark?'dark':'light';themeButton.textContent=dark?'☀':'◐';themeButton.setAttribute('aria-pressed',dark);themeButton.setAttribute('aria-label',dark?'Enable light mode':'Enable dark mode')};
let savedTheme;try{savedTheme=localStorage.getItem('wisdom-theme')}catch(e){};
applyTheme(savedTheme?savedTheme==='dark':matchMedia('(prefers-color-scheme: dark)').matches);
themeButton.addEventListener('click',()=>{const dark=!document.body.classList.contains('night-mode');applyTheme(dark);try{localStorage.setItem('wisdom-theme',dark?'dark':'light')}catch(e){}});
const languageButton=document.querySelector('.language');
const applyLanguage=malayalam=>{document.documentElement.lang=malayalam?'ml':'en';document.body.classList.toggle('malayalam',malayalam);languageButton.textContent=malayalam?'English':'മലയാളം';languageButton.setAttribute('aria-pressed',malayalam);languageButton.setAttribute('aria-label',malayalam?'Switch to English':'Switch to Malayalam');translateInterface(malayalam);renderQ();};
let savedLanguage;try{savedLanguage=localStorage.getItem('wisdom-language')}catch(e){};
languageButton.addEventListener('click',()=>{const malayalam=!document.body.classList.contains('malayalam');applyLanguage(malayalam);try{localStorage.setItem('wisdom-language',malayalam?'ml':'en')}catch(e){}});
document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{let r=el.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)*.12,y=(e.clientY-r.top-r.height/2)*.15;el.style.transform=`translate(${x}px,${y}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
const counters=document.querySelectorAll('[data-count]');let counted=false;const countUp=()=>{if(counted)return;let y=document.querySelector('.counter-row').getBoundingClientRect().top;if(y>innerHeight*.78)return;counted=true;counters.forEach(el=>{let end=+el.dataset.count,start=performance.now(),dur=1500;let tick=t=>{let n=Math.min(1,(t-start)/dur);el.textContent=Math.floor((1-Math.pow(1-n,3))*end).toLocaleString();if(n<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)})};addEventListener('scroll',countUp,{passive:true});countUp();
const questions=[
  {tag:'YOUR RELATIONSHIP · നിങ്ങളുടെ ബന്ധം',ml:'താങ്കൾ ഒരു ഫോൺ അഡിക്റ്റ് ആണോ?',en:'Do you feel addicted to your phone?',a:[['അതെ','Yes',4],['അല്ല','No',1],['അറിയില്ല','I’m not sure',2]]},
  {tag:'WHAT OTHERS NOTICE · മറ്റുള്ളവർ കാണുന്നത്',ml:'“24 മണിക്കൂറും ഫോണിലാണ്…” എന്ന് വീട്ടുകാരോ കൂട്ടുകാരോ പറയാറുണ്ടോ?',en:'Do family or friends say you are on your phone all day?',a:[['സ്ഥിരമായി','Always',4],['ഇടക്കൊക്കെ','Sometimes',3],['അപൂർവ്വമായി','Rarely',2],['ഇതുവരെ ആരും പറഞ്ഞിട്ടില്ല','No one has said this',1]]},
  {tag:'DAILY CHECKS · ദിവസേനയുള്ള അൺലോക്കുകൾ',ml:'ഒരു ദിവസം എത്ര തവണ മൊബൈൽ സ്ക്രീൻ അൺലോക്ക് ചെയ്യാറുണ്ട്?',en:'How many times do you unlock your mobile screen in a day?',a:[['200-ൽ കൂടുതൽ','More than 200',4],['100–200','100–200',3],['50–100','50–100',2],['50-ൽ താഴെ','Under 50',1]]},
  {tag:'PHANTOM PINGS · നോട്ടിഫിക്കേഷൻ തോന്നൽ',ml:'ഫോൺ റിംഗ് ചെയ്യുന്നതായോ നോട്ടിഫിക്കേഷൻ വന്നതായോ തോന്നാറുണ്ടോ?',en:'Do you sometimes feel your phone is ringing or that you received a notification?',a:[['മിക്ക സമയങ്ങളിലും','Almost always',4],['ഫ്രീ സമയങ്ങളിൽ','Mostly in free moments',3],['ഇടക്കൊക്കെ','Sometimes',2],['ഇതുവരെ ഉണ്ടായിട്ടില്ല','Never',1]]},
  {tag:'YOUR MORNING · രാവിലെ',ml:'ഉണർന്ന് ആദ്യം ചെയ്യുന്നത് WhatsApp / Facebook / Instagram പരിശോധിക്കലാണോ?',en:'Is checking WhatsApp, Facebook, or Instagram the first thing you do after waking up?',a:[['അതെ','Yes',4],['ചിലപ്പോൾ','Sometimes',2],['അല്ല','No',1],['അറിയില്ല','I’m not sure',2]]},
  {tag:'MEALTIME · ഭക്ഷണസമയം',ml:'ഭക്ഷണം കഴിക്കുമ്പോഴുള്ള ഫോൺ ഉപയോഗം എങ്ങനെയാണ്?',en:'How would you describe your phone use while eating?',a:[['സ്ക്രോൾ ചെയ്യാതെ ഭക്ഷണം കഴിക്കാൻ ബുദ്ധിമുട്ടാണ്','I feel something is missing without scrolling',4],['എന്തെങ്കിലും കാണാറുണ്ട്','I usually watch something',3],['ഇടക്കൊക്കെ ഉപയോഗിക്കും','Sometimes',2],['തീരെ ഉപയോഗിക്കാറില്ല','I do not use it while eating',1]]},
  {tag:'BATHROOM HABIT · ടോയ്ലറ്റ് സമയം',ml:'ടോയ്ലറ്റിൽ പോകുമ്പോൾ ഫോൺ ഉപയോഗം എങ്ങനെയാണ്?',en:'How do you use your phone when you go to the toilet?',a:[['മിക്ക സമയങ്ങളിലും ഉപയോഗിക്കും','Almost always',4],['പ്രത്യേക സാഹചര്യങ്ങളിൽ','Only in certain situations',3],['ഇടക്കൊക്കെ','Sometimes',2],['ഫോൺ കൊണ്ടുപോകാറില്ല','I do not take it with me',1]]},
  {tag:'YOUR NIGHT · രാത്രി',ml:'രാത്രി വൈകിയോ എല്ലാവരും ഉറങ്ങിയ ശേഷമോ ഫോൺ ഉപയോഗിക്കുന്ന ശീലമുണ്ടോ?',en:'Do you use your phone late at night or after everyone else has gone to bed?',a:[['മിക്ക ദിവസങ്ങളിലും','Most days',4],['തനിച്ചാകുന്ന ദിവസങ്ങളിൽ','When I’m alone',3],['ചിലപ്പോഴൊക്കെ','Sometimes',2],['തീരെ ഇല്ല','Never',1]]},
  {tag:'SOCIAL FEEDBACK · പ്രതികരണങ്ങൾ',ml:'പോസ്റ്റുകൾക്കും സ്റ്റാറ്റസുകൾക്കും കിട്ടുന്ന views / likes / comments ഇടക്കിടെ ചെക്ക് ചെയ്യാറുണ്ടോ?',en:'Do you frequently check the views, likes, comments, or hearts on your posts and statuses?',a:[['അധിക സമയങ്ങളിലും','Most of the time',4],['കുറച്ചധികം സമയം','Quite often',3],['ഇടക്കൊക്കെ','Sometimes',2],['ഇല്ല','No',1]]},
  {tag:'GAMING · ഗെയിമിംഗ്',ml:'ഫോണിൽ എത്ര ഗെയിം ആപ്പുകൾ ഉണ്ട്?',en:'How many game apps do you have on your phone?',a:[['10 അല്ലെങ്കിൽ കൂടുതൽ','10 or more',4],['5–9','5–9',3],['1–4','1–4',2],['0 — ഗെയിമുകൾ കളിക്കാറില്ല','0 — I do not play games',1]]},
  {tag:'SLEEP · ഉറക്കം',ml:'നിരന്തരമുള്ള സ്ക്രീൻ ഉപയോഗം ഉറക്കസമയത്തെയോ sleep pattern-നെയോ ബാധിച്ചിട്ടുണ്ടോ?',en:'Has constant screen use affected your sleep time or sleep pattern?',a:[['ഉണ്ട്','Yes',4],['കുറച്ചൊക്കെ ബാധിക്കും','Somewhat',3],['അറിയില്ല','I’m not sure',2],['ഇല്ല','No',1]]},
  {tag:'PRIVACY · സ്വകാര്യത',ml:'താങ്കളുടെ ഫോൺ മറ്റൊരാൾ പരിശോധിക്കുന്നതിൽ ഭയമുണ്ടോ?',en:'Are you afraid of someone checking your phone?',a:[['ഉണ്ട്','Yes',4],['ചെറിയ ഭയമുണ്ട്','A little',3],['എന്റെ സാന്നിധ്യത്തിൽ പ്രശ്നമില്ല','Not when I’m present',2],['ഇല്ല','No',1]]},
  {tag:'TOGETHER TIME · ഒന്നിച്ചുള്ള സമയം',ml:'കുടുംബം സംസാരിക്കുമ്പോഴോ പങ്കാളിയോടൊപ്പമുള്ള സമയത്തോ ഫോൺ ഉപയോഗം കൂടാറുണ്ടോ?',en:'Does your phone use increase during family conversations or time with your partner?',a:[['ഉണ്ട്','Yes',4],['ഇടക്കൊക്കെ','Sometimes',3],['പ്രത്യേക സാഹചര്യങ്ങളിൽ മാത്രം','Only in special situations',2],['ഇല്ല','No',1]]},
  {tag:'CONTROL · നിയന്ത്രണം',ml:'അമിത സ്ക്രീൻ ഉപയോഗം നിയന്ത്രിക്കാനുള്ള പരിശ്രമങ്ങൾ പരാജയപ്പെട്ടിട്ടുണ്ടോ?',en:'Have efforts to control excessive screen use failed?',a:[['പലതവണ ശ്രമിച്ചു, പൂർണ്ണമായി നിർത്താനായില്ല','I have tried many times but could not stop fully',4],['ശ്രമിച്ചു, വിജയിച്ചിട്ടില്ല','I tried but did not succeed',3],['ഇതുവരെ ശ്രമിച്ചിട്ടില്ല','I have never tried',2],['വളരെ കുറച്ചേ ഉപയോഗിക്കൂ','I use screens very little',1]]},
  {tag:'YESTERDAY · ഇന്നലെ',ml:'ഇന്നലെ എത്ര സമയം സ്ക്രീൻ ഉപയോഗിച്ചു?',en:'How much screen time did you use yesterday?',a:[['10 മണിക്കൂറോ കൂടുതൽ','10 hours or more',4],['6–10 മണിക്കൂർ','6–10 hours',3],['3–6 മണിക്കൂർ','3–6 hours',2],['3 മണിക്കൂറിൽ താഴെ','Under 3 hours',1]]},
  {tag:'ON THE ROAD · ഡ്രൈവിംഗ്',ml:'Driving സമയത്ത് സോഷ്യൽ മീഡിയ ഉപയോഗിക്കാറുണ്ടോ?',en:'Do you use social media while driving?',a:[['ഉണ്ട്','Yes',4],['ചില സന്ദർഭങ്ങളിൽ','Sometimes',3],['അത്യാവശ്യ ഘട്ടങ്ങളിൽ മാത്രം','Only in an emergency',2],['ഇല്ല','No',1]]}
];
const interfaceTranslations={
  '.nav-links a:nth-child(1)':['Why now','എന്തുകൊണ്ട് ഇപ്പോൾ'],'.nav-links a:nth-child(2)':['Brain lab','ബ്രെയിൻ ലാബ്'],'.nav-links a:nth-child(3)':['Gallery','ഗാലറി'],'.nav-links a:nth-child(4)':['Check in','സ്വയം പരിശോധിക്കൂ'],'.nav-links a:nth-child(5)':['The way back','തിരിച്ചുവരവിന്റെ വഴി'],'.nav-cta':['Take the check <span>↗</span>','പരിശോധന തുടങ്ങൂ <span>↗</span>'],
  '.hero-text':['Your phone is designed to hold your attention. This is a space to notice the pull, understand the pattern, and choose a little more of your own life.','നിങ്ങളുടെ ശ്രദ്ധ പിടിച്ചുനിർത്താനാണ് ഫോൺ രൂപകൽപ്പന ചെയ്തിരിക്കുന്നത്. ആ വലിച്ചിഴച്ചൽ തിരിച്ചറിയാനും, ശീലങ്ങൾ മനസ്സിലാക്കാനും, സ്വന്തം ജീവിതത്തിനായി കുറച്ചുകൂടി സമയം കണ്ടെത്താനുമുള്ള ഇടമാണിത്.'],
  '.hero-actions .button':['Start the conversation <b>↓</b>','സംഭാഷണം തുടങ്ങൂ <b>↓</b>'],'.hero-actions .text-link':['Check your screen time <span>→</span>','നിങ്ങളുടെ സ്ക്രീൻ സമയം പരിശോധിക്കൂ <span>→</span>'],
  '.pressure h2':['One more scroll.<br>Then another.','ഒന്നുകൂടി സ്ക്രോൾ.<br>പിന്നെയും ഒന്ന്.'],'.pressure .intro':['The platforms are designed to keep us close. Not because we are weak—but because the pull is engineered to feel personal.','നമ്മളെ പിടിച്ചുനിർത്താനായാണ് ഈ പ്ലാറ്റ്‌ഫോമുകൾ രൂപകൽപ്പന ചെയ്തിരിക്കുന്നത്. നമ്മൾ ദുർബലരായതുകൊണ്ടല്ല; ആ ആകർഷണം വ്യക്തിപരമായി തോന്നുന്ന രീതിയിലാണ് അത് സൃഷ്ടിച്ചിരിക്കുന്നത്.'],
  '.check-copy h2':['How are you,<br><em>really?</em>','നിങ്ങൾക്ക്<br><em>ശരിക്കും സുഖമാണോ?</em>'],'.check-copy>p:not(.eyebrow)':['Built for real days, not perfect ones. Take this private 16-question phone-use check-in and receive one gentle, practical next step.','തികഞ്ഞ ദിവസങ്ങൾക്കല്ല, യഥാർത്ഥ ദിവസങ്ങൾക്കായുള്ളതാണ് ഇത്. സ്വകാര്യമായ 16 ചോദ്യങ്ങളുള്ള ഫോൺ-ഉപയോഗ പരിശോധന പൂർത്തിയാക്കി, പ്രായോഗികമായ ഒരു ചെറിയ അടുത്ത പടി കണ്ടെത്തൂ.'],
  '.journey-title h2':['You don’t have to<br>go offline to <em>come alive.</em>','ജീവിതത്തിലേക്ക്<br><em>തിരിച്ചുവരാൻ</em> ഓഫ്‌ലൈൻ ആകേണ്ടതില്ല.'],'.final-cta h2':['Start changing<br><em>today.</em>','മാറ്റം തുടങ്ങൂ<br><em>ഇന്നുതന്നെ.</em>'],'.final-cta>p:not(.eyebrow)':['A little less noise. A little more of your life.','അൽപം കുറവ് ശബ്ദം. നിങ്ങളുടെ ജീവിതത്തിന് അൽപം കൂടുതൽ ഇടം.'],'.final-cta .button':['Begin your check-in <b>↓</b>','പരിശോധന തുടങ്ങൂ <b>↓</b>']
};
function translateInterface(malayalam){Object.entries(interfaceTranslations).forEach(([selector,copy])=>{const element=document.querySelector(selector);if(element)element.innerHTML=copy[malayalam?1:0]});document.title=malayalam?'വിശ്ഡം സ്റ്റുഡന്റ്സ് കേരള — ശ്രദ്ധയോടെ ജീവിക്കൂ.':'Wisdom Students Kerala — Look up.'}
let qi=0,score=0;const content=document.getElementById('quizContent'),qno=document.getElementById('questionNo'),bar=document.getElementById('quizProgress'),steps=document.querySelectorAll('.check-steps span');
function updateSteps(){const completed=Math.ceil((qi+1)/questions.length*steps.length);steps.forEach((step,i)=>step.classList.toggle('active',i<completed))}
function renderQ(){let q=questions[qi],malayalam=document.body.classList.contains('malayalam'),number=String(qi+1).padStart(2,'0');qno.textContent=`${number} / ${String(questions.length).padStart(2,'0')}`;bar.style.width=((qi+1)/questions.length*100)+'%';updateSteps();content.classList.remove('question-in');void content.offsetWidth;content.classList.add('question-in');content.innerHTML=`<p class="quiz-type">${malayalam?q.tag.split(' · ')[1]||q.tag:q.tag.split(' · ')[0]}</p><h3 lang="${malayalam?'ml':'en'}">${malayalam?q.ml:q.en}</h3><div class="answers">${q.a.map(([ml,en,value])=>`<button type="button" data-answer="${value}" lang="${malayalam?'ml':'en'}"><span>${malayalam?ml:en}</span><b aria-hidden="true">→</b></button>`).join('')}</div>`;content.querySelectorAll('button').forEach(b=>b.onclick=()=>{score+=+b.dataset.answer;b.disabled=true;qi++;setTimeout(()=>qi<questions.length?renderQ():result(),180)})}
function result(){const malayalam=document.body.classList.contains('malayalam');qno.textContent=malayalam?'നിങ്ങളുടെ ഫലം':'YOUR SNAPSHOT';bar.style.width='100%';steps.forEach(step=>step.classList.add('active'));let risk=Math.max(0,Math.round((score-questions.length)/(questions.length*3)*100)),isHigh=risk>=66,isMid=risk>=34,title=isHigh?'Your attention is asking for more space.':isMid?'A few small changes could make a real difference.':'You have a steady foundation to protect.',mlTitle=isHigh?'നിങ്ങളുടെ ശ്രദ്ധയ്ക്ക് കൂടുതൽ ഇടം വേണം.':isMid?'ചെറിയ മാറ്റങ്ങൾ വലിയ വ്യത്യാസം ഉണ്ടാക്കും.':'നിങ്ങൾക്ക് സംരക്ഷിക്കാവുന്ന നല്ലൊരു അടിത്തറയുണ്ട്.',tip=isHigh?'Tonight, charge your phone outside the bedroom.':isMid?'Choose one meal to keep phone-free today.':'Keep your first 15 minutes phone-free tomorrow.',mlTip=isHigh?'ഇന്ന് രാത്രി ഫോൺ കിടപ്പുമുറിക്ക് പുറത്ത് ചാർജിന് വയ്ക്കൂ.':isMid?'ഇന്ന് ഒരു ഭക്ഷണസമയം ഫോൺ ഇല്ലാതെ ആക്കൂ.':'നാളെ ഉണർന്ന ശേഷമുള്ള ആദ്യ 15 മിനിറ്റ് ഫോൺ ഇല്ലാതെ സൂക്ഷിക്കൂ.';content.innerHTML=`<p class="quiz-type" lang="${malayalam?'ml':'en'}">${malayalam?'നിങ്ങളുടെ ഡിജിറ്റൽ ശീലം':'YOUR DIGITAL WELLBEING'}</p><div class="snapshot"><div class="snapshot-ring" style="--p:${risk}%"><b>${risk}</b><small>${malayalam?'സൂചിക / 100':'risk / 100'}</small></div><div><h3 lang="${malayalam?'ml':'en'}">${malayalam?mlTitle:title}</h3></div></div><div class="result-tip" lang="${malayalam?'ml':'en'}">✦ <span>${malayalam?'ഇന്ന് പരീക്ഷിക്കൂ':'Try this today'}</span> ${malayalam?mlTip:tip}<br><small>${malayalam?'ഇത് രോഗനിർണയമല്ല — നിങ്ങളുടെ ശീലങ്ങൾ ശ്രദ്ധിക്കാൻ ഒരു ചെറിയ തുടക്കമാണ്.':'This is not a diagnosis — just a small start to notice your habits.'}</small></div><div class="answers result-actions"><button type="button" data-tool-link>${malayalam?'ഒരു ചെറിയ ഉപകരണം തിരഞ്ഞെടുക്കൂ':'Pick a small tool'} <b aria-hidden="true">↓</b></button><button type="button" data-reset>${malayalam?'വീണ്ടും തുടങ്ങൂ':'Start again'} ↻</button></div>`;content.querySelector('[data-reset]').onclick=()=>{qi=0;score=0;renderQ()};content.querySelector('[data-tool-link]').onclick=()=>document.querySelector('.toolkit').scrollIntoView({behavior:'smooth'})}
document.querySelector('.quiz-close').onclick=()=>{qi=0;score=0;renderQ()};applyLanguage(savedLanguage==='ml');
let toastTimer;const showToast=message=>{const toast=document.querySelector('.tool-toast');toast.firstChild.textContent=`${message} `;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),3200)};
document.querySelectorAll('.tool-action').forEach(button=>button.addEventListener('click',()=>{button.innerHTML='Added to today <b>✓</b>';button.disabled=true;button.closest('.tool-card').classList.add('active-tool');showToast('A small win counts. Keep going.')}));
const resetModes={soft:{title:'A softer start.',time:'9:30 PM',task:'Keep your first 15 minutes phone-free.'},focus:{title:'Make space to think.',time:'7:00 AM',task:'Choose one 45-minute focus block.'},family:{title:'A room for us.',time:'8:00 PM',task:'Share one phone-free meal together.'}};
document.querySelectorAll('.mode').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.mode').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false')});button.classList.add('active');button.setAttribute('aria-pressed','true');let mode=resetModes[button.dataset.mode];document.getElementById('modeTitle').textContent=mode.title;document.getElementById('focusTime').textContent=mode.time;document.getElementById('challengeText').textContent=mode.task}));
document.getElementById('focusToggle').addEventListener('click',e=>{let on=e.currentTarget.classList.toggle('on');e.currentTarget.setAttribute('aria-pressed',on);e.currentTarget.querySelector('span').textContent=on?'On':'Off'});
document.getElementById('challengeDone').addEventListener('click',e=>{e.currentTarget.innerHTML='Done today <b>✓</b>';e.currentTarget.disabled=true;document.getElementById('winLabel').textContent='1 / 3 complete';document.querySelector('.day.current i').textContent='✓';document.querySelector('.day.current').classList.add('done');document.getElementById('streak').textContent='02';showToast('Today’s win is recorded.')});
document.querySelector('[data-save-thought]').addEventListener('click',()=>showToast('Your reflection is saved for this visit.'));
document.querySelector('.lab-more').addEventListener('click',()=>showToast('Your reset plan stays private on this device.'));
document.querySelectorAll('.coming-soon').forEach(item=>item.addEventListener('click',()=>showToast('This reading is coming soon.')));

const brainStates={
  2:{tag:'FOCUS & BALANCE',title:'Your attention has room to breathe.',text:'Around 2 hours can leave more room for focused work, movement, rest, and time with people. What matters most is how those hours fit into your day.',meter:'24%',level:'STEADY',challenge:'Keep one 25-minute focus block notification-free.',region:'calm'},
  5:{tag:'ATTENTION & RECOVERY',title:'Your attention is working harder.',text:'At around 5 hours, frequent checking and switching can make it harder to stay with one task. A short screen-free pause is a useful reset.',meter:'56%',level:'BUILDING',challenge:'Take a 10-minute screen-free break.',region:'focus'},
  8:{tag:'ATTENTION, REST & RECOVERY',title:'Your screen is taking a bigger share of your day.',text:'At around 8 hours, digital activity can take a substantial part of waking time. Notice what it may be replacing: sleep, movement, focus, connection, and recovery.',meter:'82%',level:'HIGH',challenge:'Keep your phone away for the final 30 minutes before bed.',region:'rest'}
};
const brainRegions={
  focus:{tag:'ATTENTION & FOCUS',title:'Give your attention a little room.',text:'Rapid switching and constant alerts can make it harder to stay with one task. Try a 25-minute notification-free block.'},
  rest:{tag:'REST & SLEEP',title:'Let your mind power down.',text:'A calmer final hour helps create a clearer boundary between scrolling and sleep. Try leaving your phone outside the bedroom tonight.'},
  reward:{tag:'REWARD LOOP',title:'Pause before the next check.',text:'Likes, messages, and novelty can create a strong pull to check again. Take one slow breath before you open the next app.'},
  calm:{tag:'CALM & CONNECTION',title:'Make space to feel present.',text:'A few screen-free minutes can help your mind settle and make room for the people and moments around you.'}
};
let activeBrainHours=5,brainScore=0,completedMissions=0;
const updateBrainCopy=region=>{const content=brainRegions[region];document.getElementById('brainTag').textContent=content.tag;document.getElementById('brainTitle').textContent=content.title;document.getElementById('brainText').textContent=content.text;document.getElementById('questStatus').textContent=`Exploring ${content.tag.toLowerCase()}`;document.querySelectorAll('.brain-region').forEach(item=>item.classList.toggle('active',item.dataset.region===region))};
const setBrainHours=hours=>{const state=brainStates[hours];activeBrainHours=hours;document.querySelectorAll('.time-option').forEach(button=>{const on=+button.dataset.hours===hours;button.classList.toggle('active',on);button.setAttribute('aria-pressed',on)});document.getElementById('brainHours').textContent=`${hours}h 00m`;document.getElementById('brainMeter').style.width=state.meter;document.getElementById('brainLevel').textContent=state.level;document.getElementById('missionText').textContent=state.challenge;document.getElementById('missionNumber').textContent=`MISSION ${Math.min(completedMissions+1,3)} OF 3`;updateBrainCopy(state.region)};
const resetBrain=()=>{brainScore=0;completedMissions=0;document.getElementById('brainScore').textContent='00';document.querySelectorAll('.quest-orbs i').forEach(orb=>orb.classList.remove('done'));const done=document.getElementById('missionDone');done.disabled=false;done.innerHTML='I did it <span>+25</span>';setBrainHours(activeBrainHours);document.getElementById('questStatus').textContent='Choose a brain zone to begin'};
document.querySelectorAll('.time-option').forEach(button=>button.addEventListener('click',()=>setBrainHours(+button.dataset.hours)));
document.querySelectorAll('.brain-region').forEach(region=>{const choose=()=>updateBrainCopy(region.dataset.region);region.addEventListener('click',choose);region.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();choose()}})});
document.getElementById('missionDone').addEventListener('click',event=>{if(completedMissions>=3)return;completedMissions++;brainScore=Math.min(100,brainScore+25);document.getElementById('brainScore').textContent=String(brainScore).padStart(2,'0');document.querySelectorAll('.quest-orbs i')[completedMissions-1].classList.add('done');document.getElementById('missionNumber').textContent=`MISSION ${Math.min(completedMissions+1,3)} OF 3`;document.getElementById('questStatus').textContent=completedMissions===3?'Three small wins completed.':'Nice work — one small win recorded.';if(completedMissions===3){event.currentTarget.disabled=true;event.currentTarget.innerHTML='Complete <span>✓</span>'}else event.currentTarget.innerHTML='I did it <span>+25</span>'});
document.getElementById('brainReset').addEventListener('click',resetBrain);
setBrainHours(5);

document.querySelectorAll('.notice').forEach(notice=>notice.addEventListener('click',()=>{
  const snoozed=notice.classList.toggle('snoozed');
  notice.setAttribute('aria-pressed',snoozed);
  notice.title=snoozed?'Notification paused':'Pause this notification';
}));
